# Generated by Django 3.2.2 on 2021-05-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descritpion',
            new_name='description',
        ),
    ]
