# Generated by Django 3.2.2 on 2021-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
