# Generated by Django 3.2.2 on 2021-05-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_avatar_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='avatar_image',
            new_name='task_image',
        ),
    ]
