# Generated by Django 3.2.2 on 2021-05-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_avatar_image_todo_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
