# Generated by Django 3.2.2 on 2021-05-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
